pushing a new release Version 💡

diff --git a/jenkinsFile b/jenkinsFile
--- a/jenkinsFile
+++ b/jenkinsFile
@@ -31,58 +31,59 @@ pipeline {
                 sh 'mvn jacoco:report'
             }
         }
-         stage('Start Nexus and SonarQube') {
-                    steps {
-                        script {
-                            sh 'docker-compose -f docker-compose-nexus-sonarqube.yml up -d --build'
-                            sleep(180)
+        stage('Start Nexus and SonarQube') {
+            steps {
+                script {
+                    // Clean up any previous containers before starting new ones
+                    sh 'docker-compose -f docker-compose-nexus-sonarqube.yml down || true'
+                    sh 'docker-compose -f docker-compose-nexus-sonarqube.yml up -d --build'
+                    sleep(180)  // Give time for Nexus and SonarQube to initialize
+                }
+            }
+        }
+        stage('Check SonarQube Connectivity') {
+            steps {
+                script {
+                    timeout(time: 5, unit: 'MINUTES') {
+                        waitUntil {
+                            def response = sh(script: 'curl -s http://192.168.33.10:9000/api/system/status', returnStdout: true).trim()
+                            return response.contains('"status":"UP"')
                         }
                     }
                 }
-          stage('Check SonarQube Connectivity') {
-                 steps {
-                     script {
-                         timeout(time: 5, unit: 'MINUTES') {
-                             waitUntil {
-                                 def response = sh(script: 'curl -s http://192.168.33.10:9000/api/system/status', returnStdout: true).trim()
-                                 return response.contains('"status":"UP"')
-                             }
-                         }
-                     }
-                 }
-             }
-      stage('MVN SONARQUBE') {
-          steps {
-              withCredentials([string(credentialsId: 'sonar-token', variable: 'SONAR_TOKEN')]) {
-                  sh '''
-                   mvn sonar:sonar \
-                  -Dsonar.host.url=http://192.168.33.10:9000 \
-                  -Dsonar.login=sqp_b8a94aa00665f8966dcdea3b76530d11f078112c
-                  '''
-              }
-          }
-      }
+            }
+        }
+        stage('MVN SONARQUBE') {
+            steps {
+                withCredentials([string(credentialsId: 'sonar-token', variable: 'SONAR_TOKEN')]) {
+                    sh '''
+                    mvn sonar:sonar \
+                    -Dsonar.host.url=http://192.168.33.10:9000 \
+                    -Dsonar.login=$SONAR_TOKEN
+                    '''
+                }
+            }
+        }
+        stage('Deploy') {
+            steps {
+                withCredentials([usernamePassword(credentialsId: 'nexus-credentials', passwordVariable: 'NEXUS_PASSWORD', usernameVariable: 'NEXUS_USERNAME')]) {
+                    sh """
+                        echo "<settings>
+                            <servers>
+                                <server>
+                                    <id>deploymentRepo</id>
+                                    <username>${NEXUS_USERNAME}</username>
+                                    <password>${NEXUS_PASSWORD}</password>
+                                </server>
+                            </servers>
+                        </settings>" > ~/.m2/settings.xml
 
-  stage('Deploy') {
-      steps {
-          withCredentials([usernamePassword(credentialsId: 'nexus-credentials', passwordVariable: 'NEXUS_PASSWORD', usernameVariable: 'NEXUS_USERNAME')]) {
-              sh """
-                  echo "<settings>
-                      <servers>
-                          <server>
-                              <id>deploymentRepo</id>
-                              <username>${NEXUS_USERNAME}</username>
-                              <password>${NEXUS_PASSWORD}</password>
-                          </server>
-                      </servers>
-                  </settings>" > ~/.m2/settings.xml
-
-                  mvn deploy -DskipTests \
-                  -DaltDeploymentRepository=deploymentRepo::default::http://192.168.33.10:8081/repository/maven-releases/
-              """
-          }
-      }
-  }
+                        mvn deploy -DskipTests \
+                        -DaltDeploymentRepository=deploymentRepo::default::http://192.168.33.10:8081/repository/maven-releases/
+                    """
+                }
+            }
+        }
         stage('Build Docker Image') {
             steps {
                 script {
@@ -121,51 +122,51 @@ pipeline {
             }
         }
     }
-      post {
-          always {
-              echo 'Cleaning up...'
-              sh 'docker compose down'
-           //   sh ' docker-compose -f docker-compose-nexus-sonarqube.yml down'
-          }
-          success {
-              withCredentials([usernamePassword(credentialsId: 'email-credentials', passwordVariable: 'EMAIL_PASSWORD', usernameVariable: 'EMAIL_USERNAME')]) {
-                  emailext(
-                      to: "${EMAIL_USERNAME}",
-                      subject: "Build Successful: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
-                      body: """
-  Hello,
+    post {
+        always {
+            echo 'Cleaning up...'
+            sh 'docker compose down'
+            // sh 'docker-compose -f docker-compose-nexus-sonarqube.yml down'
+        }
+        success {
+            withCredentials([usernamePassword(credentialsId: 'email-credentials', passwordVariable: 'EMAIL_PASSWORD', usernameVariable: 'EMAIL_USERNAME')]) {
+                emailext(
+                    to: "${EMAIL_USERNAME}",
+                    subject: "Build Successful: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
+                    body: """
+Hello,
 
-  The build for job '${env.JOB_NAME}' (Build #${env.BUILD_NUMBER}) has completed successfully.
+The build for job '${env.JOB_NAME}' (Build #${env.BUILD_NUMBER}) has completed successfully.
 
-  You can check the console output for more details at: [Build Log](${env.BUILD_URL})
+You can check the console output for more details at: [Build Log](${env.BUILD_URL})
 
-  Thank you for your attention!
+Thank you for your attention!
 
-  Best regards,
-  Your Jenkins CI/CD
-  """
-                  )
-              }
-          }
-          failure {
-              withCredentials([usernamePassword(credentialsId: 'email-credentials', passwordVariable: 'EMAIL_PASSWORD', usernameVariable: 'EMAIL_USERNAME')]) {
-                  emailext(
-                      to: "${EMAIL_USERNAME}",
-                      subject: "Build Failed: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
-                      body: """
-  Hello,
+Best regards,
+Your Jenkins CI/CD
+"""
+                )
+            }
+        }
+        failure {
+            withCredentials([usernamePassword(credentialsId: 'email-credentials', passwordVariable: 'EMAIL_PASSWORD', usernameVariable: 'EMAIL_USERNAME')]) {
+                emailext(
+                    to: "${EMAIL_USERNAME}",
+                    subject: "Build Failed: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
+                    body: """
+Hello,
 
-  The build for job '${env.JOB_NAME}' (Build #${env.BUILD_NUMBER}) has failed.
+The build for job '${env.JOB_NAME}' (Build #${env.BUILD_NUMBER}) has failed.
 
-  You can check the console output for more details at: [Build Log](${env.BUILD_URL})
+You can check the console output for more details at: [Build Log](${env.BUILD_URL})
 
-  Please investigate the issue.
+Please investigate the issue.
 
-  Best regards,
-  Your Jenkins CI/CD
-  """
-                  )
-              }
-          }
-      }
-  }
+Best regards,
+Your Jenkins CI/CD
+"""
+                )
+            }
+        }
+    }
+}
